# MumbleDJ
# By Matthieu Grieger
# Copyright (c) 2016 Matthieu Grieger (MIT License)
# config.yaml

api_keys:

    # YouTube API key.
    youtube: ""

    # SoundCloud API key.
    # NOTE: The API key is your client ID.
    soundcloud: ""


defaults:

    # Default comment to be applied to bot.
    # NOTE: If you do not want a comment by default, set to empty string ("").
    comment: "Bonjour ! Je suis un robot. Envoyez !help pour une liste de commandes."

    # Default channel for the bot to enter upon connection.
    # NOTE: If you wish for the bot to connect to the root channel, set to empty string ("").
    channel: ""

    # Command to use to play audio files. The two supported choices are "ffmpeg" and "avconv".
    player_command: "ffmpeg"


queue:

    # Ratio that must be met or exceeded to trigger a track skip.
    track_skip_ratio: 0.5

    # Ratio that must be met or exceeded to trigger a playlist skip.
    playlist_skip_ratio: 0.5

    # Maximum track duration in seconds. Set to 0 for unrestricted duration.
    max_track_duration: 0

    # Maximum tracks per playlist. Set to 0 for unrestricted playlists.
    max_tracks_per_playlist: 50

    # Is shuffling enabled when the bot starts?
    automatic_shuffle_on: false

    # Announce track information at the beginning of audio playback?
    announce_new_tracks: true


connection:

    # Address bot should attempt to connect to.
    address: "127.0.0.1"

    # Port bot should attempt to connect to.
    port: "64738"

    # Password for connecting to server.
    # NOTE: If no password, set to empty string ("").
    password: ""

    # Username for MumbleDJ.
    username: "MumbleDJ"

    # Filepath to user p12 file for authenticating as a registered user.
    # NOTE: If no p12 file is needed, set to empty string ("").
    user_p12: ""

    # Should the bot attempt an insecure connection?
    # An insecure connection does not verify the certificate of the server for
    # consistency. It is best to leave this on, but disable it if you are having
    # issues connecting to a server or are running multiple instances of MumbleDJ.
    insecure: false

    # Filepath to certificate file.
    # NOTE: If no certificate file is needed, set to empty string ("").
    cert: ""

    # Filepath to certificate key file.
    # NOTE: If no key is needed, set to empty string ("").
    key: ""

    # Access tokens to initialize the bot with, separated by commas.
    # NOTE: If no access tokens are needed, set to empty string ("").
    access_tokens: ""

    # Should the bot automatically attempt to retry connection to a server after disconnecting?
    retry_enabled: true

    # How many times should the bot attempt to reconnect to the server?
    retry_attempts: 10

    # How many seconds should the bot wait in-between connection retry attempts?
    retry_interval: 5


cache:

    # Cache songs as they are downloaded?
    enabled: false

    # Maximum total file size of cache directory in MiB.
    maximum_size: 512

    # Period of time that should elapse before a song is cleared from the cache, in hours.
    expire_time: 24

    # Period of time between each check of the cache for expired items, in minutes.
    check_interval: 5

    # Directory to store cached items. Environment variables are able to be used here.
    directory: "$HOME/.cache/mumbledj"


volume:

    # Default volume.
    default: 0.2

    # Lowest volume allowed.
    lowest: 0.01

    # Highest volume allowed.
    highest: 0.8


admins:

    # Enable admins?
    # NOTE: If this is set to false, any command can be executed by any user.
    enabled: true

    # List of admin names.
    # NOTE: It is recommended that the names in this list are registered on the
    # server so that imposters cannot execute admin commands.
    names:
        - "SuperUser"


commands:

    # Character used to designate commands from normal text messages.
    # NOTE: Only one character (the first) is used.
    prefix: "!"

    common_messages:
        no_tracks_error: "Il n'y a pas de titres dans la liste de lecture."
        caching_disabled_error: "Le cache est actuellement désactivé."

    # Below is a list of the commands supported by MumbleDJ. Each command has
    # three configurable options:
    # aliases: A list of names that can be used to execute the command.
    # is_admin: true = only admins can execute the command, false = anyone can execute the command.
    # description: Description shown for the command when the help command is executed.
    # messages: Various messages that may be sent as a text message from the command. Useful for translating
    #           strings to other languages. Do NOT remove strings that begin with "%" (such as "%s", "%d", etc.)
    #           as they substituted with runtime data. Removing these strings will cause the bot to misbehave.
    add:
        aliases:
            - "add"
            - "a"
        is_admin: false
        description: "Ajoute un titre ou une playlist à la liste de lecture."
        messages:
            no_url_error: "Une URL doit être envoyée avec cette commande."
            no_valid_tracks_error: "Aucun contenu valide n'a été trouvé avec le(s) lien(s)."
            tracks_too_long_error: "La ou les titre(s) sont soit trop longs, soit une erreur est survenue. Rien n'a été ajouté."
            one_track_added: "<b>%s</b> a ajouté <b>1</b> titre à la liste de lecture :<br><i>%s</i> depuis %s"
            many_tracks_added: "<b>%s</b> a ajouté <b>%d</b> titres à la liste de lecture."
            num_tracks_too_long: "<br><b>%d</b> titre(s) ignorés à cause d'une erreur ou de la durée du contenu."

    addnext:
        aliases:
            - "addnext"
            - "an"
        is_admin: true
        description: "Ajoute un titre ou une playlist juste après le titre en cours à la liste de lecture."
        # addnext uses the messages defined for add.

    cachesize:
        aliases:
            - "cachesize"
            - "cs"
        is_admin: true
        description: "Retourne la taille utilisée par le cache, en MiB, si le cache est activé."
        messages:
            current_size: "La taille du cache est actuellement de <b>%.2v MiB</b>."

    currenttrack:
        aliases:
            - "currenttrack"
            - "currentsong"
            - "current"
        is_admin: false
        description: "Retourne des informations du titre en cours, s'il y en a un."
        messages:
            current_track: "Le titre en cours est <i>%s</i>, ajouté par <b>%s</b>."

    forceskip:
        aliases:
            - "forceskip"
            - "fs"
        is_admin: true
        description: "Passe immédiatement le titre actuel."
        messages:
            track_skipped: "Le titre en cours a été sauté par <b>%s</b>."

    forceskipplaylist:
        aliases:
            - "forceskipplaylist"
            - "fsp"
        is_admin: true
        description: "Passe imméditement la playlist actuelle."
        messages:
            no_playlist_error: "Le titre actuel ne vient pas d'une playlist."
            playlist_skipped: "La playlist actuelle a été sauté par <b>%s</b>."

    help:
        aliases:
            - "help"
            - "h"
        is_admin: false
        description: "Retourne la liste des commandes."
        messages:
            commands_header: "<br><b>Commandes :</b><br>"
            admin_commands_header: "<br><b>Commandes Admin :</b><br>"

    joinme:
        aliases:
            - "joinme"
            - "join"
        is_admin: true
        description: "Déplace MumbleDJ vers votre salon, s'il est inactif."
        messages:
            others_are_listening_error: "Des utilisateurs sont actuellement en train de m'écouter."
            in_your_channel: "Me voici !"

    kill:
        aliases:
            - "kill"
            - "k"
        is_admin: true
        description: "Arrête le robot et vide le cache."

    listtracks:
        aliases:
            - "listtracks"
            - "listsongs"
            - "list"
            - "l"
        is_admin: false
        description: "Retourne la liste de lecture."
        messages:
            invalid_integer_error: "Un nombre invalide a été reçu."
            track_listing: "<b>%d</b> : <i>%s</i>, ajouté par <b>%s</b>.<br>"

    move:
        aliases:
            - "move"
            - "m"
        is_admin: true
        description: "Déplace le robot dans un salon, précisé via un argument."
        messages:
            no_channel_provided_error: "Le salon de destination doit être précisé."
            channel_doesnt_exist_error: "Le salon indiqué ne semble pas exister."
            move_successful: "Le robot a été déplacé vers <b>%s</b>."

    nexttrack:
        aliases:
            - "nexttrack"
            - "nextsong"
            - "next"
        is_admin: false
        description: "Retourne des informations du titre suivant, s'il y en a un."
        messages:
            current_track_only_error: "Il n'y a pas de titre suivant !"
            next_track: "Le titre suivant est <i>%s</i>, ajouté par <b>%s</b>."

    numcached:
        aliases:
            - "numcached"
            - "nc"
        is_admin: true
        description: "Retourne le nombre de titres en cache, si le cache est activé."
        messages:
            num_cached: "Il y a actuellement <b>%d</b> titres dans le cache."

    numtracks:
        aliases:
            - "numtracks"
            - "numsongs"
            - "nt"
        is_admin: false
        description: "Retourne le nombre de titres dans la liste de lecture."
        messages:
            one_track: "Il y a <b>1</b> titre dans la liste de lecture."
			plural_tracks: "Il y a <b>%d</d> titres dans la liste de lecture."

    pause:
        aliases:
            - "pause"
        is_admin: false
        description: "Met la lecture en pause."
        messages:
            no_audio_error: "Soit l'audio est déjà mise sur pause, soit il n'y a pas de titres à lire."
            paused: "<b>%s</b> a mis la lecture en pause."

    register:
        aliases:
            - "register"
            - "reg"
        is_admin: true
        description: "Enregistre le robot sur le serveur."
        messages:
            already_registered_error: "Je suis déjà enregistré sur le serveur."
            registered: "Je suis maintenant enregistré sur le serveur."

    reload:
        aliases:
            - "reload"
            - "r"
        is_admin: true
        description: "Recharge le fichier de configuration."
        messages:
            reloaded: "Le fichier de configuration a été rechargé."

    reset:
        aliases:
            - "reset"
            - "re"
        is_admin: true
        description: "Vide la liste de lecture."
        messages:
            queue_reset: "<b>%s</b> a vidé la liste de lecture."

    resume:
        aliases:
            - "resume"
        is_admin: false
        description: "Reprends la lecture du titre, mis en pause."
        messages:
            audio_error: "Soit l'audio est déjà en lecture, soit il n'y a pas de titres à lire."
            resumed: "<b>%s</b> a repris la lecture."

    setcomment:
        aliases:
            - "setcomment"
            - "comment"
            - "sc"
        is_admin: true
        description: "Défini le commentaire de MumbleDJ dans Mumble."
        messages:
            comment_removed: "Le commentaire du robot a été retiré."
            comment_changed: "Le commentaire du robot a été changé vers : %s"

    shuffle:
        aliases:
            - "shuffle"
            - "shuf"
            - "sh"
        is_admin: true
        description: "Mélange la liste de lecture."
        messages:
            not_enough_tracks_error: "Il n'y a pas assez de titres dans la liste de lecture pour la mélanger."
            shuffled: "La liste de lecture a été mélangée."

    skip:
        aliases:
            - "skip"
            - "s"
        is_admin: false
        description: "Voter pour sauter le titre actuel."
        messages:
            already_voted_error: "Vous avez déjà voté pour sauter ce titre."
            voted: "<b>%s</b> a voté pour sauter le titre."

    skipplaylist:
        aliases:
            - "skipplaylist"
            - "sp"
        is_admin: false
        description: "Voter pour sauter la playlist actuelke."
        messages:
            no_playlist_error: "Le titre actuel ne vient pas d'une playlist."
            already_voted_error: "Vous avez déjà voté pour sauter cette playlist."
            voted: "<b>%s</b> a voté pour sauter la playlist."

    toggleshuffle:
        aliases:
            - "toggleshuffle"
            - "toggleshuf"
            - "togshuf"
            - "tsh"
        is_admin: true
        description: "Active/désactive le mode de lecture aléatoire."
        messages: 
            toggled_off: "La lecture aléatoire a été désactivée."
            toggled_on: "La lecture aléatoire a été activée."


    version:
        aliases:
            - "version"
            - "v"
        is_admin: false
        description: "Retourne la version actuelle de MumbleDJ."
        messages:
            version: "MumbleDJ version : <b>%s</b>"

    volume:
        aliases:
            - "volume"
            - "vol"
        is_admin: false
        description: "Change le volume si la valeur est indiquée, sinon retourne le volume actuel."
        messages:
            parsing_error: "Le volume demandé n'a pas pu être lu correctement."
            out_of_range_error: "Le volume doit être entre <b>%.2f</b> et <b>%.2f</b>."
            current_volume: "Le volume est actuellement à <b>%.2f</b>."
            volume_changed: "<b>%s</b> a changé le volume à <b>%.2f</b>."
